default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'password') %>
  host: <%= ENV.fetch('MYSQL_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('MYSQL_PORT', '3307') %>
  database: <%= ENV.fetch('MYSQL_DATABASE', 'backend_dev') %>

development:
  <<: *default

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  database: backend
