services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: "DockerfileDev"
    command: /bin/sh -c "env | sort && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=backend_dev
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3306
    env_file:
      - ./backend/.env
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  db-data:
