require:
  - rubocop-ast
  - rubocop-graphql
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3.4
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
