---
name: ast
version: '2.4'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 2a4c50bcdef253f577aac568db63e97e10901b98
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
